export const frasesArray = [
    { id: 1, frase: "Nos afligimos más en la imaginación que en la realidad.", autor: "Séneca" },
    { id: 2, frase: "Lo que sucede no te afecta tanto como tu juicio sobre lo que sucede.", autor: "Epicteto" },
    { id: 3, frase: "La calidad de tus pensamientos es la felicidad de tu vida.", autor: "Marco Aurelio" },
    { id: 4, frase: "Desea que los sucesos ocurran como ocurren, y tu vida fluirá bien.", autor: "Epicteto" },
    { id: 5, frase: "Mientras esperamos, la vida pasa.", autor: "Séneca" },
    { id: 6, frase: "Tienes poder sobre tu mente, no sobre los acontecimientos.", autor: "Marco Aurelio" },
    { id: 7, frase: "La verdadera riqueza no es poseer mucho, sino necesitar poco.", autor: "Epicteto" },
    { id: 8, frase: "Un hombre valiente es libre.", autor: "Séneca" },
    { id: 9, frase: "Nos arrepentimos sin causa y dejamos de disfrutar por temor al futuro.", autor: "Séneca" },
    { id:10, frase: "Cuanto más valoras lo que no controlas, menos control tienes.", autor: "Epicteto" },
    { id:11, frase: "Sé tolerante con los demás y estricto contigo mismo.", autor: "Marco Aurelio" },
    { id:12, frase: "La diversión del buen hombre es actuar bien.", autor: "Marco Aurelio" },
    { id:13, frase: "Es suficiente ser virtuoso para ser feliz.", autor: "Epicteto" },
    { id:14, frase: "Vive como si ya hubieses muerto.", autor: "Marco Aurelio" },
    { id:15, frase: "El obstáculo es el camino.", autor: "Marco Aurelio" },
    { id:16, frase: "No prolongues el tiempo: ¡vive ya!", autor: "Séneca" },
    { id:17, frase: "Un hombre sabio no se aflige por lo que no tiene.", autor: "Séneca" },
    { id:18, frase: "Si algo no es justo, no lo hagas; si no es verdadero, no lo digas.", autor: "Marco Aurelio" },
    { id:19, frase: "El alma se tiñe con el color de sus pensamientos.", autor: "Marco Aurelio" },
    { id:20, frase: "La dificultad muestra de qué está hecho un hombre.", autor: "Epicteto" },
    { id:21, frase: "La vida es como una leyenda: no importa que sea larga, sino que esté bien narrada.", autor: "Séneca" },
    { id:22, frase: "Un hombre sin pasiones está tan cerca de la estupidez que sólo le falta abrir la boca para caer en ella.", autor: "Séneca" },
    { id:23, frase: "No nos atrevemos a muchas cosas porque son difíciles, pero son difíciles porque no nos atrevemos a hacerlas.", autor: "Séneca" },
    { id:24, frase: "A través de lo áspero se llega a las estrellas.", autor: "Séneca" },
    { id:25, frase: "La mayor rémora de la vida es la espera del mañana y la pérdida del día de hoy.", autor: "Séneca" },
    { id:26, frase: "La ira: un ácido que puede hacer más daño al recipiente en la que se almacena que en cualquier cosa sobre la que se vierte.", autor: "Séneca" },
    { id:27, frase: "No hay nadie menos afortunado que el hombre a quien la adversidad olvida, pues no tiene oportunidad de ponerse a prueba.", autor: "Séneca" },
    { id:28, frase: "El alma noble posee la gran cualidad de apasionarse por las cosas honestas", autor: "Séneca" },
    { id:29, frase: "Importa mucho más lo que tú pienses de ti mismo que lo que otros piensen de tí.", autor: "Séneca" },
    { id:30, frase: "Decir lo que sentimos. Sentir lo que decimos. Concordar las palabras con la vida.", autor: "Séneca" },
    { id:31, frase: "En tres tiempos se divide la vida: en presente, pasado y futuro. De éstos, el presente es brevísimo; el futuro, dudoso; el pasado, cierto.", autor: "Séneca" },
    { id:32, frase: "Cuando se está en medio de las adversidades, ya es tarde para ser cauto.", autor: "Séneca" },
    { id:33, frase: "No hay mayor causa de llanto que no poder llorar.", autor: "Séneca" },
    { id:34, frase: "¿Quieres saber que es libertad? No ser esclavo de ninguna cosa, de ninguna necesidad, de ningún azar, reducir la fortuna a términos de equidad.", autor: "Séneca" },
    { id:35, frase: "Sabed que cuando uno es amigo de sí mismo, lo es también de todo el mundo.", autor: "Séneca" },
    { id:36, frase: "Nunca hizo rico al hombre el dinero, porque solamente le sirve para aumentar su codicia.", autor: "Séneca" },
    { id:37, frase: "Lo que las leyes no prohíben, puede prohibirlo la honestidad.", autor: "Séneca" },
    { id:38, frase: "Vive con el inferior tal cual quisieras que el superior viviera contigo. Siempre haz con el esclavo no más que lo que quisieras hiciera contigo un dueño.", autor: "Séneca" },
    { id:39, frase: "Hay ciertas cosas que para hacerlas bien no basta haberlas aprendido.", autor: "Séneca" },
    { id:40, frase: "Te diré cuál es el verdadero placer y de dónde viene: de la buena conciencia, de las rectas intenciones, de las buenas acciones, del menosprecio de las cosas del azar, del aire plácido y lleno de seguridad, de la vida que siempre pisa el mismo camino.", autor: "Séneca" },
    { id:41, frase: "Desechado, pues, de ti otro cuidado, pon sólo la atención en unos pocos preceptos. Y acuérdate que cada uno no vive más que el presente, indeciblemente pequeño. El resto de la vida, o ya se acabó de vivir, o es incierto. Brevísimo es, pues, el instante que cada uno vive, brevísimo el espacio donde habita, brevísima la fama de la posteridad.", autor: "Marco Aurelio" },
    { id:42, frase: "En ningún lugar encuentra el hombre refugio más apacible, más tranquilo, que en su propia alma.", autor: "Marco Aurelio" },
    { id:43, frase: "El mundo es una mutación continua: la vida, una imaginación.", autor: "Marco Aurelio" },
    { id:44, frase: "Las cosas mismas no llegan al alma, sino que permanecen en el exterior, inamovibles; las inquietudes provienen únicamente del modo que interiormente tienes de opinar.", autor: "Marco Aurelio" },
  ];

  