export const frasesArray = [
    { id: 1, frase: "Nos afligimos más en la imaginación que en la realidad.", autor: "Séneca" },
    { id: 2, frase: "Lo que sucede no te afecta tanto como tu juicio sobre lo que sucede.", autor: "Epicteto" },
    { id: 3, frase: "La calidad de tus pensamientos es la felicidad de tu vida.", autor: "Marco Aurelio" },
    { id: 4, frase: "Desea que los sucesos ocurran como ocurren, y tu vida fluirá bien.", autor: "Epicteto" },
    { id: 5, frase: "Mientras esperamos, la vida pasa.", autor: "Séneca" },
    { id: 6, frase: "Tienes poder sobre tu mente, no sobre los acontecimientos.", autor: "Marco Aurelio" },
    { id: 7, frase: "La verdadera riqueza no es poseer mucho, sino necesitar poco.", autor: "Epicteto" },
    { id: 8, frase: "Un hombre valiente es libre.", autor: "Séneca" },
    { id: 9, frase: "Nos arrepentimos sin causa y dejamos de disfrutar por temor al futuro.", autor: "Séneca" },
    { id:10, frase: "Cuanto más valoras lo que no controlas, menos control tienes.", autor: "Epicteto" },
    { id:11, frase: "Sé tolerante con los demás y estricto contigo mismo.", autor: "Marco Aurelio" },
    { id:12, frase: "La diversión del buen hombre es actuar bien.", autor: "Marco Aurelio" },
    { id:13, frase: "Es suficiente ser virtuoso para ser feliz.", autor: "Epicteto" },
    { id:14, frase: "Vive como si ya hubieses muerto.", autor: "Marco Aurelio" },
    { id:15, frase: "El obstáculo es el camino.", autor: "Marco Aurelio" },
    { id:16, frase: "No prolongues el tiempo: ¡vive ya!", autor: "Séneca" },
    { id:17, frase: "Un hombre sabio no se aflige por lo que no tiene.", autor: "Séneca" },
    { id:18, frase: "Si algo no es justo, no lo hagas; si no es verdadero, no lo digas.", autor: "Marco Aurelio" },
    { id:19, frase: "El alma se tiñe con el color de sus pensamientos.", autor: "Marco Aurelio" },
    { id:20, frase: "La dificultad muestra de qué está hecho un hombre.", autor: "Epicteto" },
    { id:21, frase: "La vida es como una leyenda: no importa que sea larga, sino que esté bien narrada.", autor: "Séneca" },
    { id:22, frase: "Un hombre sin pasiones está tan cerca de la estupidez que sólo le falta abrir la boca para caer en ella.", autor: "Séneca" },
    { id:23, frase: "No nos atrevemos a muchas cosas porque son difíciles, pero son difíciles porque no nos atrevemos a hacerlas.", autor: "Séneca" },
    { id:24, frase: "A través de lo áspero se llega a las estrellas.", autor: "Séneca" },
    { id:25, frase: "La mayor rémora de la vida es la espera del mañana y la pérdida del día de hoy.", autor: "Séneca" },
    { id:26, frase: "La ira: un ácido que puede hacer más daño al recipiente en la que se almacena que en cualquier cosa sobre la que se vierte.", autor: "Séneca" },
    { id:27, frase: "No hay nadie menos afortunado que el hombre a quien la adversidad olvida, pues no tiene oportunidad de ponerse a prueba.", autor: "Séneca" },
    { id:28, frase: "El alma noble posee la gran cualidad de apasionarse por las cosas honestas", autor: "Séneca" },
    { id:29, frase: "Importa mucho más lo que tú pienses de ti mismo que lo que otros piensen de tí.", autor: "Séneca" },
    { id:30, frase: "Decir lo que sentimos. Sentir lo que decimos. Concordar las palabras con la vida.", autor: "Séneca" },
    { id:31, frase: "En tres tiempos se divide la vida: en presente, pasado y futuro. De éstos, el presente es brevísimo; el futuro, dudoso; el pasado, cierto.", autor: "Séneca" },
    { id:32, frase: "Cuando se está en medio de las adversidades, ya es tarde para ser cauto.", autor: "Séneca" },
    { id:33, frase: "No hay mayor causa de llanto que no poder llorar.", autor: "Séneca" },
    { id:34, frase: "¿Quieres saber que es libertad? No ser esclavo de ninguna cosa, de ninguna necesidad, de ningún azar, reducir la fortuna a términos de equidad.", autor: "Séneca" },
    { id:35, frase: "Sabed que cuando uno es amigo de sí mismo, lo es también de todo el mundo.", autor: "Séneca" },
    { id:36, frase: "Nunca hizo rico al hombre el dinero, porque solamente le sirve para aumentar su codicia.", autor: "Séneca" },
    { id:37, frase: "Lo que las leyes no prohíben, puede prohibirlo la honestidad.", autor: "Séneca" },
    { id:38, frase: "Vive con el inferior tal cual quisieras que el superior viviera contigo. Siempre haz con el esclavo no más que lo que quisieras hiciera contigo un dueño.", autor: "Séneca" },
    { id:39, frase: "Hay ciertas cosas que para hacerlas bien no basta haberlas aprendido.", autor: "Séneca" },
    { id:40, frase: "Te diré cuál es el verdadero placer y de dónde viene: de la buena conciencia, de las rectas intenciones, de las buenas acciones, del menosprecio de las cosas del azar, del aire plácido y lleno de seguridad, de la vida que siempre pisa el mismo camino.", autor: "Séneca" },
    { id:41, frase: "Desechado, pues, de ti otro cuidado, pon sólo la atención en unos pocos preceptos. Y acuérdate que cada uno no vive más que el presente, indeciblemente pequeño. El resto de la vida, o ya se acabó de vivir, o es incierto. Brevísimo es, pues, el instante que cada uno vive, brevísimo el espacio donde habita, brevísima la fama de la posteridad.", autor: "Marco Aurelio" },
    { id:42, frase: "En ningún lugar encuentra el hombre refugio más apacible, más tranquilo, que en su propia alma.", autor: "Marco Aurelio" },
    { id:43, frase: "El mundo es una mutación continua: la vida, una imaginación.", autor: "Marco Aurelio" },
    { id:44, frase: "Las cosas mismas no llegan al alma, sino que permanecen en el exterior, inamovibles; las inquietudes provienen únicamente del modo que interiormente tienes de opinar.", autor: "Marco Aurelio" },
    { id:45, frase: "No tener nada que te excite, que te acucie, que con su ataque o con su anuncio ponga a prueba el temple de tu alma, estar echado en un ocio sin inquietudes no es tranquilidad sino indolencia.", autor: "Séneca" },
    { id:46, frase: "Por muy elevado que la fortuna haya puesto a un hombre, siempre necesita un amigo.", autor: "Séneca" },
    { id:47, frase: "Dar consejos al hombre avisado es superfluo; darlos al ignorante es poca cosa.", autor: "Séneca" },
    { id:48, frase: "La vida no es ni un bien ni un mal, es sólo ocasión de bien y de mal.", autor: "Séneca" },
    { id:49, frase: "Más dura la memoria de las injurias recibidas que de los beneficios.", autor: "Séneca" },
    { id:50, frase: "El que tiene mucho desea más, lo cual demuestra que no tiene bastante; pero el que tiene bastante ha llegado un punto al que el rico no llega jamás.", autor: "Séneca" },
    { id:51, frase: "Compra sólo lo necesario, no lo conveniente. Lo innecesario, aunque cueste un solo céntimo, es caro.", autor: "Séneca" },
    { id:52, frase: "Los brazos de la fortuna no son largos. Suelen apoyarse en quien más se acerca a ella.", autor: "Séneca" },
    { id:53, frase: "La felicidad no mira dónde nace, sino adónde puede llegar.", autor: "Séneca" },
    { id:54, frase: "Algunas veces incluso vivir es un acto de coraje.", autor: "Séneca" },
    { id:55, frase: "Si quieres que tu secreto sea guardado, guárdalo tú mismo.", autor: "Séneca" },
    { id:56, frase: "A algunos se les considera grandes porque también se cuenta el pedestal.", autor: "Séneca" },
    { id:57, frase: "El destino conduce a quien lo acepta, y arrastra al que rehúsa admitirlo.", autor: "Séneca" },
    { id:58, frase: "La llaga del amor, quien la sana, la crea.", autor: "Séneca" },
    { id:59, frase: "Admira a quien lo intenta, aunque fracase.", autor: "Séneca" },
    { id:60, frase: "Un solo bien puede haber en el mal: la vergüenza de haberlo hecho.", autor: "Séneca" },
    { id:61, frase: "Para ser feliz hay que vivir en guerra con las propias pasiones y en paz con las de los demás.", autor: "Séneca" },
    { id:62, frase: "Merece salir engañado el que, al hacer un beneficio, tenía en cuenta la recompensa.", autor: "Séneca" },
    { id:63, frase: "Jamás se descubriría nada, si nos consideraremos satisfechos con las cosas descubiertas.", autor: "Séneca" },
    { id:64, frase: "Necesitamos la vida entera para aprender a vivir, y también, cosa sorprendente, para aprender a morir.", autor: "Séneca" },
    { id:65, frase: "La tristeza, aunque esté siempre justificada, muchas veces sólo es pereza. Nada necesita menos esfuerzo que estar triste.", autor: "Séneca" },
    { id:66, frase: "El que no quiere vivir sino entre justos, que viva en el desierto.", autor: "Séneca" },
    { id:67, frase: "La naturaleza nos ha dado las semillas del conocimiento, no el conocimiento mismo.", autor: "Séneca" },
    { id:68, frase: "No hay cosa más fuerte que el verdadero amor.", autor: "Séneca" },
    { id:69, frase: "El primer arte que deben aprender los que aspiran al poder es el de ser capaces de soportar el odio.", autor: "Séneca" },
    { id:70, frase: "El hombre más poderoso es el que es dueño de sí mismo.", autor: "Séneca" },
    { id:71, frase: "No existe ningún genio sin un toque de demencia.", autor: "Séneca" },
    { id:72, frase: "Peores son los odios ocultos que los descubiertos.", autor: "Séneca" },
    { id:73, frase: "Prefiero molestar con la verdad que complacer con adulaciones.", autor: "Séneca" },
    { id:74, frase: "El que siempre busca grandezas, alguna vez la encuentra.", autor: "Séneca" },
    { id:75, frase: "No es necesaria la fortuna para sólo subsistir.", autor: "Séneca" },
    { id:76, frase: "Una buena conciencia no teme a ningún testigo.", autor: "Séneca" },
    { id:77, frase: "Escucha aún a los pequeños, porque nada es despreciable en ellos.", autor: "Séneca" },
    { id:78, frase: "Incontenida, la cólera es frecuentemente más dañina que la injuria que la provoca.", autor: "Séneca" },
    { id:79, frase: "La esclavitud más denigrante es la de ser esclavo de uno mismo.", autor: "Séneca" },
    { id:80, frase: "Este día que tanto temes por ser el último, es la aurora del día eterno.", autor: "Séneca" },
    { id:81, frase: "Un gran marinero puede navegar aunque sus velas sean de alquiler.", autor: "Séneca" },
    { id:82, frase: "El que es prudente es moderado; el que es moderado es constante; el que es constante es imperturbable; el que es imperturbable vive sin tristeza; el que vive sin tristeza es feliz; luego el prudente es feliz.", autor: "Séneca" },
    { id:83, frase: "Ingrato es el que por miedo es agradecido.", autor: "Séneca" },
    { id:84, frase: "Tanto más crece el esfuerzo, cuanto más consideramos la grandeza de lo emprendido.", autor: "Séneca" },
    { id:85, frase: "No hay, en mi dictamen, hombre que aprecie más la virtud y la siga con más gusto, que el que por no hacer traición a su conciencia, ha perdido la reputación de hombre de bien.", autor: "Séneca" },
    { id:86, frase: "Desdichado es el que por tal se tiene.", autor: "Séneca" },
    { id:87, frase: "La recompensa de una buena acción es haberla hecho.", autor: "Séneca" },
    { id:88, frase: "La amistad y la enemistad proceden de la voluntad.", autor: "Séneca" },
    { id:89, frase: "No recibimos una vida corta, sino que nosotros la acortamos. No somos de ella indigentes, sino manirrotos.", autor: "Séneca" },
    { id:90, frase: "Nuestra naturaleza está en la acción. El reposo presagia la muerte.", autor: "Séneca" },
    { id:91, frase: "La conversación es la expresión de nuestro modo de pensar.", autor: "Séneca" },
    { id:92, frase: "Las obras se tienen medio terminadas cuando se han comenzado bien.", autor: "Séneca" },
    { id:93, frase: "El amor en su esencia es el fuego espiritual.", autor: "Séneca" },
    { id:94, frase: "No hay árbol recio ni consistente sino aquel que el viento azota con frecuencia.", autor: "Séneca" },
    { id:95, frase: "No hay viento favorable para el que no sabe dónde va.", autor: "Séneca" },
    { id:96, frase: "Las obras se tienen medio terminadas cuando se han comenzado bien.", autor: "Séneca" },
    { id:97, frase: "Feas palabras, aún livianamente dichas ofenden.", autor: "Séneca" },
    { id:98, frase: "Lo que de raíz se aprende nunca del todo se olvida.", autor: "Séneca" },
    { id:99, frase: "No es pobre el que tiene poco, sino el que mucho desea.", autor: "Séneca" },
    { id:100, frase: "Los hombres aman sus vicios y al mismo tiempo los odian.", autor: "Séneca" },
    { id:101, frase: "Cuanto mayor es la prosperidad tanto menor se debe confiar en ella.", autor: "Séneca" },
    { id:102, frase: "Quien da pronto, da dos veces.", autor: "Séneca" },
    { id:103, frase: "Languidece la virtud sin adversarios.", autor: "Séneca" },
    { id:104, frase: "El arrepentimiento es el remordimiento aceptado.", autor: "Séneca" },
    { id:105, frase: "Mientras nosotros posponemos, la vida acelera.", autor: "Séneca" },
    { id:106, frase: "Un mal amigo siempre se define por un signo.", autor: "Séneca" },
    { id:107, frase: "Sin razón se queja del mar el que otra vez navega.", autor: "Séneca" },
    { id:108, frase: "Con facilidad se adquiere lo preciso para la vida.", autor: "Séneca" },
    { id:109, frase: "Procuramos olvidar lo que, traído a la memoria, nos entristece.", autor: "Séneca" },
    { id:110, frase: "La armonía total de este mundo está formada por una natural aglomeración de discordancias.", autor: "Séneca" },
    { id:112, frase: "Bueno es tener fama, pero más seguro es tener dinero.", autor: "Séneca" },
    { id:113, frase: "Contra la ira, dilación.", autor: "Séneca" },
    { id:114, frase: "Confiesa el delito el que huye del juicio.", autor: "Séneca" },
    { id:115, frase: "Dos veces vence el que en la victoria se vence a sí.", autor: "Séneca" },
    { id:116, frase: "Muchas veces es valor el conservar la vida.", autor: "Séneca" },
    { id:117, frase: "Ajeno es todo lo que nos viene en deseo.", autor: "Séneca" },
    { id:118, frase: "Desgracia imprevista nos hiere más fuertemente.", autor: "Séneca" },
    { id:119, frase: "El peor enemigo es el traidor.", autor: "Séneca" },
    { id:120, frase: "Más dañosa es la abundancia que viene sobre gran codicia.", autor: "Séneca" },
    { id:121, frase: "Sé útil primero a los demás, si quieres ser útil a ti mismo.", autor: "Séneca" },
    { id:122, frase: "Muchos habrían podido llegar a la sabiduría si no se hubiesen creído demasiado sabios.", autor: "Séneca" },
    { id:123, frase: "Las buenas costumbres se conforman unas con otras, y por eso duran.", autor: "Séneca" },
    { id:124, frase: "Ofensa hace a los buenos el que a los malos perdona.", autor: "Séneca" },
    { id:125, frase: "Todo lo debemos consultar con el amigo, más primero debemos consultar si lo es.", autor: "Séneca" },
    { id:126, frase: "El tiempo es como un río que arrastra rápidamente todo lo que nace.", autor: "Marco Aurelio" },
    { id:127, frase: "La vida es larga si sabes aprovecharla.", autor: "Séneca" },
    { id:128, frase: "No es porque las cosas sean difíciles que no nos atrevemos, es porque no nos atrevemos que son difíciles.", autor: "Séneca" },
    { id:129, frase: "La virtud es algo que podemos practicar en todo momento.", autor: "Séneca" },
    { id:130, frase: "No es la riqueza lo que hace al hombre feliz, sino su comportamiento.", autor: "Séneca" },
    { id:131, frase: "Es más importante controlar tus deseos que someter al enemigo.", autor: "Séneca" },
    { id:132, frase: "Ningún descubrimiento fue hecho sin un primer paso arriesgado.", autor: "Séneca" },
    { id:133, frase: "La verdadera nobleza está en ser superior a lo que fuiste ayer.", autor: "Séneca" },
    { id:134, frase: "Aprende a disfrutar de lo que tienes antes de desear lo que no tienes.", autor: "Séneca" },
    { id:135, frase: "La paciencia es amarga, pero su fruto es dulce.", autor: "Séneca" },
    { id:136, frase: "A veces, una vida modesta proporciona más felicidad que una llena de logros vacíos.", autor: "Séneca" },
    { id:137, frase: "El hombre más feliz es aquel que depende menos de la felicidad.", autor: "Séneca" },
    { id:138, frase: "Es sabio el que tiene más preguntas que respuestas.", autor: "Séneca" },
    { id:139, frase: "Un corazón lleno de gratitud es un imán para los milagros.", autor: "Séneca" },
    { id:140, frase: "El que conoce su ignorancia es sabio.", autor: "Séneca" },
    { id:141, frase: "Nadie te puede hacer más daño que tus propios pensamientos.", autor: "Séneca" },
    { id:142, frase: "El valor de un hombre no se mide por lo que posee, sino por lo que es capaz de superar.", autor: "Séneca" },
    { id:143, frase: "Aquel que no sabe lo que busca, no entiende lo que encuentra.", autor: "Séneca" },
    { id:144, frase: "La verdadera riqueza es estar satisfecho con poco.", autor: "Séneca" },
    { id:145, frase: "El tiempo cura lo que la razón no puede.", autor: "Séneca" },
    { id:146, frase: "El sabio no sufre los males presentes, sino los que su imaginación agranda.", autor: "Séneca" },
    { id:147, frase: "Nadie es verdaderamente libre si no se gobierna a sí mismo.", autor: "Séneca" },
    { id:148, frase: "Las dificultades fortalecen la mente, como el trabajo lo hace con el cuerpo.", autor: "Séneca" },
    { id:149, frase: "La sabiduría comienza en la reflexión sobre uno mismo.", autor: "Séneca" },
    { id:150, frase: "El que no está dispuesto a perder, tampoco está preparado para ganar.", autor: "Séneca" },
    { id:151, frase: "La mejor venganza es ser diferente a quien causó el daño.", autor: "Marco Aurelio" },
    { id:152, frase: "Lo que no es útil para la colmena, no es útil para la abeja.", autor: "Marco Aurelio" },
    { id:153, frase: "Si no conviene, no lo hagas; si no es verdad, no lo digas. Sé dueño de tus inclinaciones.", autor: "Marco Aurelio" },
    { id:154, frase: "Realiza cada una de tus acciones como si fuera la última de tu vida.", autor: "Marco Aurelio" },
    { id:155, frase: "No obres como si fueras a vivir mil años; obra como si el fin estuviera muy cerca.", autor: "Marco Aurelio" },
    { id:156, frase: "La dulzura, cuando es sincera, es una fuerza invencible.", autor: "Marco Aurelio" },
    { id:157, frase: "El arte de vivir se asemeja más a la lucha que a la danza.", autor: "Marco Aurelio" },
    { id:158, frase: "Tranquilo a la vez que resuelto, alegre a la par que consistente, es el hombre que en todo sigue la razón.", autor: "Marco Aurelio" },
    { id:159, frase: "Una sola es la luz del sol, aunque la obstaculicen muros, montes, incontables impedimentos.", autor: "Marco Aurelio" },
    { id:160, frase: "No malgastes más tiempo argumentando acerca de lo que debe ser un buen hombre. Trata de ser uno.", autor: "Marco Aurelio" },
    { id:161, frase: "No permitas que tu memoria se enajene de las cosas que tienes, sino de las que te hagan falta.", autor: "Marco Aurelio" },
    { id:162, frase: "Tienes poder sobre tu mente, no sobre los acontecimientos. Date cuenta de esto y encontrarás la fuerza.", autor: "Marco Aurelio" },
    { id:163, frase: "Todas las cosas se hallan entrelazadas entre sí y su común vínculo es sagrado y casi ninguna es extraña a la otra, porque todas están coordinadas y contribuyen al orden del mismo mundo.", autor: "Marco Aurelio" },
    { id:164, frase: "Cuánto tiempo ahorra el que no se da la vuelta para ver lo que su vecino hace, dice o piensa.", autor: "Marco Aurelio" },
    { id:165, frase: "Hemos nacido para colaborar, al igual que los pies, las manos, los párpados, las hileras de dientes, superiores e inferiores. Obrar, pues, como adversarios los unos de los otros es contrario a la naturaleza.", autor: "Marco Aurelio" },
    { id:166, frase: "Todo lo que escuchamos es una opinión, no un hecho. Todo lo que vemos es una perspectiva, no la verdad.", autor: "Marco Aurelio" },
    { id:167, frase: "Comenzar es la mitad del trabajo, comienza nuevamente con la mitad restante, y habrás terminado.", autor: "Marco Aurelio" },
    { id:168, frase: "Muchas veces me pregunto cómo es que cada hombre se ama más a sí mismo que a los demás, pero a pesar de todo le da menos valor a sus propias opiniones que a las opiniones de otros.", autor: "Marco Aurelio" },
    { id:169, frase: "Si estás molesto por una causa externa, el dolor no se debe a la causa en sí misma, sino al valor que tú le das. Y tienes el poder de revocar ese valor.", autor: "Marco Aurelio" },
    { id:170, frase: "Se buscan retiros en el campo, en la costa y en el monte. Tú también sueles anhelar tales retiros. Pero todo eso es de lo más vulgar, porque puedes, en el momento que te apetezca, retirarte en ti mismo.", autor: "Marco Aurelio" },
    { id:171, frase: "Recógete en ti mismo. El guía interior racional puede, por naturaleza, bastarse a sí mismo practicando la justicia y, según eso mismo, conservando la calma.", autor: "Marco Aurelio" },
    { id:172, frase: "Habla, sea en el Senado, sea ante cualquiera, con elegancia y certeramente. Utiliza una terminología sana.", autor: "Marco Aurelio" },
    { id:173, frase: "Recibe sin orgullo, despréndete sin apego.", autor: "Marco Aurelio" },
    { id:174, frase: "Recuerda que ni el futuro ni el pasado te son gravosos, sino siempre el presente. Y éste se minimiza, si lo delimitas exclusivamente a sí mismo.", autor: "Marco Aurelio" },
    { id:175, frase: "Cada vez que estés a punto de señalar un defecto en otra persona, hazte la siguiente pregunta: ¿Qué defecto en mí se parece al que estoy a punto de criticar?", autor: "Marco Aurelio" },
    { id:176, frase: "Mira hacia el pasado, con sus imperios cambiantes que se alzaron y cayeron, y serás capaz de prever el futuro.", autor: "Marco Aurelio" },
    { id:177, frase: "¿Quieres ser alabado por un hombre que se maldice a sí mismo tres veces por hora? ¿Quieres complacer a un hombre que no se complace a sí mismo?", autor: "Marco Aurelio" },
    { id:178, frase: "Si algún hombre me odia, ese es su problema. Mi única preocupación es no hacer o decir nada que merezca ese odio.", autor: "Marco Aurelio" },
    { id:179, frase: "El que teme la muerte, teme la insensibilidad u otra sensación. Pero si ya no percibes la sensibilidad, tampoco percibirás ningún mal. Y si adquieres una sensibilidad distinta, serás un ser indiferente y no cesarás de vivir.", autor: "Marco Aurelio" },
    { id:180, frase: "Nuestra vida es lo que nuestros pensamientos crean.", autor: "Marco Aurelio" },
    { id:181, frase: "Los hombres han nacido los unos para los otros. Instrúyelos o sopórtalos.", autor: "Marco Aurelio" },
    { id:182, frase: "¿Es tu reputación lo que te molesta? Mira lo rápido que somos olvidados. El abismo del tiempo eterno se traga todo.", autor: "Marco Aurelio" },
    { id:183, frase: "No desdeñes la muerte; antes bien, acógela gustosamente, en la convicción de que ésta también es una de las cosas que la naturaleza quiere.", autor: "Marco Aurelio" },
    { id:184, frase: "El que peca, peca contra sí mismo; el que comete una injusticia, contra sí la comete, y a sí mismo se daña.", autor: "Marco Aurelio" },
    { id:185, frase: "Muchas veces comete injusticia el que nada hace, no sólo el que hace algo.", autor: "Marco Aurelio" },
    { id:186, frase: "Hoy me he librado de toda circunstancia difícil, mejor dicho, eché fuera de mí todo engorro, porque éste no estaba fuera de mí, sino dentro, en mis opiniones.", autor: "Marco Aurelio" },
    { id:187, frase: "Que algo te parezca difícil, no quiere decir que nadie más sea capaz de lograrlo.", autor: "Marco Aurelio" },
    { id:188, frase: "Imperturbabilidad con respecto a lo que acontece como resultado de una causa exterior y justicia en las cosas que se producen por una causa que de ti proviene.", autor: "Marco Aurelio" },
    { id:189, frase: "Todo cuanto ves, muy pronto será destruido y los que han visto la destrucción dentro de muy poco serán también destruidos; y el que murió en la vejez extrema acabará igual que el que murió prematuramente.", autor: "Marco Aurelio" },
    { id:190, frase: "La pérdida no es otra cosa que una transformación.", autor: "Marco Aurelio" },
    { id:191, frase: "Cualquier cosa que te acontezca, desde la eternidad estaba preestablecida para ti, y la concatenación de causas ha entrelazado desde siempre tu subsistencia con este acontecimiento.", autor: "Marco Aurelio" },
    { id:192, frase: "Está en tu poder retirarte en ti mismo cada vez que lo desees. La tranquilidad perfecta consiste en el orden de la mente, el reino que te pertenece.", autor: "Marco Aurelio" },
    { id:193, frase: "Después de asignarte estos nombres: bueno, reservado, veraz, prudente, condescendiente, magnánimo, procura no cambiar nunca de nombre, y, si perdieras dichos nombres, emprende su búsqueda a toda prisa.", autor: "Marco Aurelio" },
    { id:194, frase: "No actúes como si fueras a vivir por diez mil años. La muerte te acecha. Mientras vivas, mientras sea posible, sé bueno.", autor: "Marco Aurelio" },
    { id:195, frase: "Detente particularmente en cada una de las acciones que haces y pregúntate si la muerte es terrible porque te priva de eso.", autor: "Marco Aurelio" },
    { id:196, frase: "Del mismo modo que los médicos siempre tienen a mano los instrumentos de hierro para las curas de urgencia, así también, conserva tú a punto los principios fundamentales para conocer las cosas divinas y las humanas.", autor: "Marco Aurelio" },
    
  ];

  